resources:
  database:
    type: redis
services:
  web:
    build: .
    port: 3000
    command: "npm run dev"
    environment:
      - PORT=3000
    resources:
      - database
  api:
    build: .
    port: 3001
    command: "npm run dev"
    environment:
     - PORT=3001
    resources:
      - database
