services:
  web:
    build: .
    port: 3000
    command: "npm run dev"
    environment:
      - PORT=3000
  api:
    build: .
    port: 3001
    command: "npm run dev"
    environment:
     - PORT=3001
