version: 2.1
orbs:
  convox: convox/orb@dev:master
workflows:
  deploy:
    jobs:
      - deploy
jobs:
  deploy:
    executor: convox/cli
    steps:
      - checkout
      - convox/deploy:
          rack: do-test
          app: nodedemo
          host: console.convox.com