version: 2.1
orbs:
  convox: convox/orb@1.4.2
workflows:
  deploy:
    jobs:
      - deploy
jobs:
  deploy:
    executor: convox/cli
    steps:
      - checkout
      - convox/deploy:
          rack: gcp
          app: nodedemo
      - convox/deploy:
          rack: aws
          app: nodedemo
          
