name: Convox Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: login
      uses: convox/action-login@v1
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
    - name: create
      uses: convox/action-create@v1
      with:
        rack: cgdemo/prod-demo
        app: nodetest
    - name: build
      id: build
      uses: convox/action-build@v1
      with:
        rack: cgdemo/prod-demo
        app: nodetest
    - name: migrate
      uses: convox/action-run@v1
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
        rack: cgdemo/prod-demo
        app: nodetest
        service: web
        release: ${{ steps.build.outputs.release }}
        command: "node -v"
    - name: promote
      uses: convox/action-promote@v1
      with:
        rack: cgdemo/prod-demo
        app: nodetest
        release: ${{ steps.build.outputs.release }}
    - name: destroy
      uses: convox/action-destroy@v1
      with:
        rack: cgdemo/prod-demo
        app: nodetest