name: Convox Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Convox Deploy
      uses: convox/action-deploy@master
      with:
        rack: cgdemo/prod-demo
        app: nodedemo
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}