name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy
      uses: convox/actions/deploy@master
      env:
        CONVOX_PASSWORD: ${{ secrets.CONVOX_DEPLOY_KEY}}
      with:
        CONVOX_HOST: console.convox.com
        CONVOX_RACK: cgdemo/prod-demo
        CONVOX_APP: nodedemo

