name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: login
      uses: convox/actions/login@multipart
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY}}
    - name: run
      uses: convox/actions/run@multipart
      with:
        rack: cgdemo/prod-demo
        app: nodedemo
        service: web
        command: "node -v"
