name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: login
      uses: convox/action-login@master
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
    - name: build
      uses: convox/action-build@master
      with:
        rack: cgdemo/prod-demo
        app: nodedemo
    - name: migrate
      uses: convox/action-run@master
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
        rack: cgdemo/prod-demo
        app: nodedemo
        service: web
        command: "node -v"
    - name: promote
      uses: convox/action-promote@master
      with:
        rack: cgdemo/prod-demo
        app: nodedemo