name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      id: build
      uses: convox/actions/build@multipart
      env:
        CONVOX_PASSWORD: ${{ secrets.CONVOX_DEPLOY_KEY}}
      with:
        CONVOX_HOST: console.convox.com
        CONVOX_RACK: cgdemo/prod-demo
        CONVOX_APP: nodedemo
    - name: output
      uses: actions/checkout@v1

