name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      id: build
      uses: convox/actions/build@multipart
      env:
        CONVOX_PASSWORD: ${{ secrets.CONVOX_DEPLOY_KEY}}
      with:
        CONVOX_HOST: console.convox.com
        CONVOX_RACK: cgdemo/prod-demo
        CONVOX_APP: nodedemo
    - name: Dump steps context
      env:
        RELEASE_ID: ${{ steps.build.outputs.release_id }}
      run: echo "$RELEASE_ID"  
    - name: echo output
      run: echo "$release_id"
          

