name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Convox CLI
      run: |
        curl -L https://convox.com/cli/linux/convox -o /tmp/convox
        sudo mv /tmp/convox /usr/local/bin/convox
        sudo chmod 755 /usr/local/bin/convox
    - name: Deploy
      env:
        CONVOX_PASSWORD: ${{ secrets.CONVOX_DEPLOY_KEY}}
        CONVOX_HOST: console.convox.com
        CONVOX_RACK: cgdemo/prod-demo
        APP: nodedemo
      run: convox deploy --app=$APP
