name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      id: build
      uses: convox/actions/build@multipart
      with:
        passowrd: ${{ secrets.CONVOX_DEPLOY_KEY}}
        rack: cgdemo/prod-demo
        app: nodedemo
    - name: run
      uses: convox/actions/run@multipart
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
        rack: cgdemo/prod-demo
        app: nodedemo
        release_id: ${{ steps.build.outputs.release_id }}
        service: web
        command: "node -v"
    - name: promote
      uses: convox/actions/promote@multipart
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
        rack: cgdemo/prod-demo
        app: nodedemo
        release_id: ${{ steps.build.outputs.release_id }}
